<?php
/**
 * Media governance read ability definitions.
 *
 * @package NpcinkAbilitiesToolkit
 */

namespace Npcink_Abilities_Toolkit\Packages\Read_Definitions;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Provides media governance read ability definitions.
 */
final class Media_Governance_Read_Definitions {
	/**
	 * Returns media governance read ability definitions.
	 *
	 * @param object $callbacks Callback owner.
	 * @return array<string,array<string,mixed>>
	 */
	public static function definitions( $callbacks ) {
		return array(
				'npcink-abilities-toolkit/list-media'      => array(
				'label'            => __( 'List Media', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Returns a paginated list of media library attachments.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'       => 'object',
					'properties' => array(
						'mime_type'         => array( 'type' => 'string' ),
						'search'            => array( 'type' => 'string' ),
						'date_from'         => array( 'type' => 'string' ),
						'date_to'           => array( 'type' => 'string' ),
						'has_empty_alt'     => array( 'type' => 'boolean', 'default' => false ),
						'has_empty_caption' => array( 'type' => 'boolean', 'default' => false ),
						'per_page'          => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 50, 'default' => 10 ),
						'page'              => array( 'type' => 'integer', 'minimum' => 1, 'default' => 1 ),
					),
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'total'    => array( 'type' => 'integer' ),
						'page'     => array( 'type' => 'integer' ),
						'per_page' => array( 'type' => 'integer' ),
						'items'    => array(
							'type'  => 'array',
							'items' => array(
								'type'       => 'object',
								'properties' => array(
									'id'        => array( 'type' => 'integer' ),
									'title'     => array( 'type' => 'string' ),
									'date'      => array( 'type' => 'string' ),
									'mime_type' => array( 'type' => 'string' ),
									'url'       => array( 'type' => 'string' ),
									'edit_link' => array( 'type' => 'string' ),
								),
								'required'   => array( 'id', 'url' ),
							),
						),
					),
					'required'   => array( 'total', 'items' ),
				),
				'execute_callback' => array( $callbacks, 'list_media' ),
			),
			'npcink-abilities-toolkit/resolve-media-attachment-by-url' => array(
				'label'            => __( 'Resolve Media Attachment By URL', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Resolves a same-site uploads URL to bounded media attachment candidates with read-only match evidence.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'url'            => array( 'type' => 'string' ),
						'max_candidates' => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 20, 'default' => 10 ),
					),
					'required'             => array( 'url' ),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array(
							'type'                 => 'object',
							'properties'           => array(
								'resolver_contract_version' => array( 'type' => 'string' ),
								'readonly'                  => array( 'type' => 'boolean' ),
								'input_url'                 => array( 'type' => 'string' ),
								'normalized_url'            => array( 'type' => 'string' ),
								'uploads_base_url'          => array( 'type' => 'string' ),
								'requested_relative_file'   => array( 'type' => 'string' ),
								'match_status'              => array( 'type' => 'string' ),
								'resolution_quality'        => array( 'type' => 'string' ),
								'attachment_id'             => array( 'type' => 'integer' ),
								'candidates'                => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
								'warnings'                  => array( 'type' => 'array', 'items' => array( 'type' => 'string' ) ),
								'boundary'                  => array( 'type' => 'object', 'additionalProperties' => true ),
							),
							'required'             => array( 'resolver_contract_version', 'readonly', 'input_url', 'normalized_url', 'uploads_base_url', 'requested_relative_file', 'match_status', 'resolution_quality', 'candidates', 'warnings', 'boundary' ),
							'additionalProperties' => false,
						),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'resolve_media_attachment_by_url' ),
			),
			'npcink-abilities-toolkit/build-inline-image-blocks' => array(
				'label'            => __( 'Build Inline Image Blocks', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Converts uploaded inline image rows into append-ready Gutenberg image blocks without writing post content.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'manage_options',
				'required_scope'   => 'cap.text.generate',
				'required_scopes'  => array( 'cap.text.generate' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'uploaded_inline_media'   => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
						'generated_inline_media'  => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
						'inline_plan'             => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
					),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array(
							'type'       => 'object',
							'properties' => array(
								'blocks'  => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
								'summary' => array( 'type' => 'object', 'additionalProperties' => true ),
							),
							'required'   => array( 'blocks', 'summary' ),
						),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'build_inline_image_blocks' ),
			),
			'npcink-abilities-toolkit/build-media-seo-assets' => array(
				'label'            => __( 'Build Media SEO Assets', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Builds a canonical media SEO enrichment asset list from article media workflow upload outputs.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'article'                   => array( 'type' => 'object', 'additionalProperties' => true ),
						'resolved_image_source'     => array( 'type' => 'object', 'additionalProperties' => true ),
						'featured_upload'           => array( 'type' => 'object', 'additionalProperties' => true ),
						'generated_featured_upload' => array( 'type' => 'object', 'additionalProperties' => true ),
						'inline_uploads'            => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
						'generated_inline_uploads'  => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
						'vision_fallback_mode'      => array( 'type' => 'string', 'enum' => array( 'off', 'auto' ), 'default' => 'auto' ),
					),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'build_media_seo_assets' ),
			),
			'npcink-abilities-toolkit/optimize-media-metadata' => array(
				'label'            => __( 'Optimize Media Metadata', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Builds deterministic media title, alt, caption, description, source, and disclosure suggestions from article and media context.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'article_title'        => array( 'type' => 'string' ),
						'article_excerpt'      => array( 'type' => 'string' ),
						'article_content'      => array( 'type' => 'string' ),
						'focus_keyword'        => array( 'type' => 'string' ),
						'vision_fallback_mode' => array( 'type' => 'string', 'enum' => array( 'off', 'auto' ) ),
						'media_assets'         => array( 'type' => array( 'array', 'null' ), 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
					),
					'required'             => array( 'media_assets' ),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'optimize_media_metadata' ),
			),
			'npcink-abilities-toolkit/position-inline-image-blocks' => array(
				'label'            => __( 'Position Inline Image Blocks', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Places generated inline image blocks after matching paragraph, heading, or anchor targets and falls back to append.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'manage_options',
				'required_scope'   => 'post.read',
				'required_scopes'  => array( 'post.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'existing_blocks' => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
						'inline_blocks'   => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
						'inline_plan'     => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
					),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array(
							'type'       => 'object',
							'properties' => array(
								'blocks'  => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
								'summary' => array( 'type' => 'object', 'additionalProperties' => true ),
							),
							'required'   => array( 'blocks', 'summary' ),
						),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'position_inline_image_blocks' ),
			),
				'npcink-abilities-toolkit/get-media-cleanup-opportunities' => array(
					'label'            => __( 'Get Media Cleanup Opportunities', 'npcink-abilities-toolkit' ),
					'description'      => __( 'Scans a bounded media inventory and returns cleanup opportunities for metadata gaps, source gaps, and likely unused assets.', 'npcink-abilities-toolkit' ),
					'category'         => 'npcink-abilities-toolkit-data',
					'capability'       => 'upload_files',
					'required_scope'   => 'media.read',
					'required_scopes'  => array( 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'mime_type' => array( 'type' => 'string' ),
						'per_page'  => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 100, 'default' => 50 ),
						'page'      => array( 'type' => 'integer', 'minimum' => 1, 'default' => 1 ),
					),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
						),
						'required'   => array( 'success', 'data' ),
					),
					'execute_callback' => array( $callbacks, 'get_media_cleanup_opportunities' ),
				),
				'npcink-abilities-toolkit/list-media-backups' => array(
					'label'            => __( 'List Media Backups', 'npcink-abilities-toolkit' ),
					'description'      => __( 'Lists recorded backup files for one attachment media operation history without mutating media.', 'npcink-abilities-toolkit' ),
					'category'         => 'npcink-abilities-toolkit-data',
					'capability'       => 'upload_files',
					'required_scope'   => 'media.read',
					'required_scopes'  => array( 'media.read' ),
					'contract_version' => 'v1',
					'source'           => 'official',
					'input_schema'     => array(
						'type'                 => 'object',
						'properties'           => array(
							'attachment_id'  => array( 'type' => 'integer', 'minimum' => 1 ),
							'include_rolled_back' => array( 'type' => 'boolean', 'default' => true ),
						),
						'required'             => array( 'attachment_id' ),
						'additionalProperties' => false,
					),
					'output_schema'    => array(
						'type'       => 'object',
						'properties' => array(
							'success' => array( 'type' => 'boolean' ),
							'data'    => array( 'type' => 'object', 'additionalProperties' => true ),
							'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
							'message' => array( 'type' => 'string' ),
						),
						'required'   => array( 'success', 'data' ),
					),
					'execute_callback' => array( $callbacks, 'list_media_backups' ),
				),
				'npcink-abilities-toolkit/build-media-inventory-fix-plan' => array(
					'label'            => __( 'Build Media Inventory Fix Plan', 'npcink-abilities-toolkit' ),
					'description'      => __( 'Maps bounded media inventory issues to reviewable metadata and cleanup actions that reuse existing governed write abilities without mutating media.', 'npcink-abilities-toolkit' ),
					'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'attachment_ids'              => array( 'type' => 'array', 'maxItems' => 50, 'items' => array( 'type' => 'integer', 'minimum' => 1 ) ),
						'mime_type'                   => array( 'type' => 'string' ),
						'search'                      => array( 'type' => 'string' ),
						'issue_types'                 => array( 'type' => 'array', 'items' => array( 'type' => 'string' ), 'default' => array( 'missing_alt', 'missing_caption', 'missing_description', 'missing_source', 'format_attention', 'possibly_unattached' ) ),
						'article_title'               => array( 'type' => 'string' ),
						'article_excerpt'             => array( 'type' => 'string' ),
						'focus_keyword'               => array( 'type' => 'string' ),
						'per_page'                    => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 50, 'default' => 20 ),
						'page'                        => array( 'type' => 'integer', 'minimum' => 1, 'default' => 1 ),
						'max_actions'                 => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 100, 'default' => 50 ),
						'include_delete_candidates'   => array( 'type' => 'boolean', 'default' => false ),
						'include_trash_parent_media'  => array( 'type' => 'boolean', 'default' => false ),
						'include_unattached_nonproduction_media' => array( 'type' => 'boolean', 'default' => false ),
					),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'build_media_inventory_fix_plan' ),
			),
			'npcink-abilities-toolkit/build-media-reference-repair-plan' => array(
				'label'            => __( 'Build Media Reference Repair Plan', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Scans post content for hard-coded URLs to a previously replaced media file and builds governed patch-post-content actions without mutating posts.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'edit_posts',
				'required_scope'   => 'post.read',
				'required_scopes'  => array( 'post.read', 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'attachment_id'      => array( 'type' => 'integer', 'minimum' => 1 ),
						'replacement_id'     => array( 'type' => 'string' ),
						'old_url'            => array( 'type' => 'string' ),
						'new_url'            => array( 'type' => 'string' ),
						'old_relative_file'  => array( 'type' => 'string' ),
						'new_relative_file'  => array( 'type' => 'string' ),
						'max_posts'          => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 50, 'default' => 20 ),
						'max_replacements_per_post' => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 20, 'default' => 20 ),
					),
					'required'             => array( 'attachment_id' ),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'build_media_reference_repair_plan' ),
			),
			'npcink-abilities-toolkit/build-media-adoption-enhancement-plan' => array(
				'label'            => __( 'Build Media Adoption Enhancement Plan', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Builds a read-only batch plan that imports a reviewed remote image, generates an optimized derivative, and optionally patches one post from an old media URL to the optimized derivative.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read', 'post.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'url'                         => array( 'type' => 'string', 'format' => 'uri', 'minLength' => 1 ),
						'post_id'                     => array( 'type' => 'integer', 'minimum' => 1 ),
						'attach_to_post_id'           => array( 'type' => 'integer', 'minimum' => 1 ),
						'old_url'                     => array( 'type' => 'string' ),
						'file_name'                   => array( 'type' => 'string', 'maxLength' => 120 ),
						'title'                       => array( 'type' => 'string' ),
						'alt'                         => array( 'type' => 'string' ),
						'caption'                     => array( 'type' => 'string' ),
						'description'                 => array( 'type' => 'string' ),
						'source_type'                 => array( 'type' => 'string', 'enum' => array( 'owned', 'ai_generated', 'stock', 'external', 'test' ), 'default' => 'external' ),
						'source_page_url'             => array( 'type' => 'string' ),
						'photographer_name'           => array( 'type' => 'string' ),
						'attribution_text'            => array( 'type' => 'string' ),
						'copyright_notice'            => array( 'type' => 'string' ),
						'target_max_width'            => array( 'type' => 'integer', 'minimum' => 320, 'maximum' => 7680, 'default' => 1920 ),
						'preferred_format'            => array( 'type' => 'string', 'enum' => array( 'webp', 'jpeg', 'png' ), 'default' => 'webp' ),
						'quality'                     => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 100, 'default' => 82 ),
						'derivative_suffix'           => array( 'type' => 'string', 'maxLength' => 48, 'default' => 'optimized' ),
						'include_reference_repair'    => array( 'type' => 'boolean', 'default' => true ),
						'max_replacements_per_post'   => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 20, 'default' => 20 ),
					),
					'required'             => array( 'url' ),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'build_media_adoption_enhancement_plan' ),
			),
			'npcink-abilities-toolkit/build-image-candidate-adoption-plan' => array(
				'label'            => __( 'Build Image Candidate Adoption Plan', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Builds a read-only batch plan for importing one reviewed image candidate, applying reviewed media metadata, and optionally setting it as a post featured image.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read', 'post.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'image_candidate'            => array( 'type' => 'object', 'additionalProperties' => true ),
						'candidate'                  => array( 'type' => 'object', 'additionalProperties' => true ),
						'download_url'               => array( 'type' => 'string', 'format' => 'uri' ),
						'image_url'                  => array( 'type' => 'string', 'format' => 'uri' ),
						'url'                        => array( 'type' => 'string', 'format' => 'uri' ),
						'post_id'                    => array( 'type' => 'integer', 'minimum' => 1 ),
						'set_featured_image'         => array( 'type' => 'boolean', 'default' => false ),
						'thumbnail_url'              => array( 'type' => 'string' ),
						'source_url'                 => array( 'type' => 'string' ),
						'source_type'                => array( 'type' => 'string', 'enum' => array( 'owned', 'ai_generated', 'stock', 'external', 'manual_upload', 'test' ), 'default' => 'external' ),
						'provider'                   => array( 'type' => 'string' ),
						'provider_origin'            => array( 'type' => 'string' ),
						'title'                      => array( 'type' => 'string' ),
						'alt'                        => array( 'type' => 'string' ),
						'description'                => array( 'type' => 'string' ),
						'attribution_text'           => array( 'type' => 'string' ),
						'photographer_name'          => array( 'type' => 'string' ),
						'copyright_notice'           => array( 'type' => 'string' ),
						'file_name'                  => array( 'type' => 'string', 'maxLength' => 120 ),
						'license_review_status'      => array( 'type' => 'string' ),
						'warnings'                   => array( 'type' => 'array', 'items' => array( 'type' => 'string' ) ),
					),
					'required'             => array(),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'build_image_candidate_adoption_plan' ),
			),
			'npcink-abilities-toolkit/build-image-candidate-review-artifact' => array(
				'label'            => __( 'Build Image Candidate Review Artifact', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Normalizes already retrieved image_candidate.v1 rows into a review-only artifact and lightweight recommendation projections without searching, generating, importing, or writing media.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'image_candidates' => array(
							'type'     => array( 'array', 'null' ),
							'maxItems' => 12,
							'items'    => array( 'type' => 'object', 'additionalProperties' => true ),
						),
						'target_field'     => array( 'type' => 'string', 'enum' => array( 'featured_image', 'paragraph_image', 'inline_image', 'setting_image' ), 'default' => 'featured_image' ),
						'candidate_limit'  => array( 'type' => array( 'integer', 'null' ), 'minimum' => 1, 'maximum' => 12, 'default' => 8 ),
					),
					'required'             => array(),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'build_image_candidate_review_artifact' ),
			),
			'npcink-abilities-toolkit/build-media-alt-caption-review-set' => array(
				'label'            => __( 'Build Media ALT/Caption Review Set', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Builds a deterministic review-only media ALT and caption candidate set from supplied media metadata and optional reviewed image-context evidence without inspecting pixels or writing media.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'media_snapshot'         => array(
							'type'                 => 'object',
							'properties'           => array(
								'snapshot_policy' => array( 'type' => 'string' ),
								'media_scope'     => array( 'type' => 'string' ),
								'media_filter'    => array( 'type' => 'string' ),
								'post_context'    => array(
									'type'                 => 'object',
									'properties'           => array(
										'post_id' => array( 'type' => 'integer' ),
										'title'   => array( 'type' => 'string' ),
									),
									'additionalProperties' => false,
								),
								'items'           => array(
									'type'     => 'array',
									'maxItems' => 30,
									'items'    => array( 'type' => 'object', 'additionalProperties' => true ),
								),
							),
							'additionalProperties' => false,
						),
						'image_context_evidence' => array(
							'type'                 => array( 'object', 'null' ),
							'properties'           => array(
								'contract_version'       => array( 'type' => 'string' ),
								'write_posture'          => array( 'type' => 'string' ),
								'direct_wordpress_write' => array( 'type' => 'boolean' ),
								'items'                  => array(
									'type'     => 'array',
									'maxItems' => 10,
									'items'    => array( 'type' => 'object', 'additionalProperties' => true ),
								),
							),
							'additionalProperties' => false,
						),
						'review_set_limit'       => array( 'type' => array( 'integer', 'null' ), 'minimum' => 1, 'maximum' => 10, 'default' => 5 ),
						'max_items'              => array( 'type' => array( 'integer', 'null' ), 'minimum' => 1, 'maximum' => 10 ),
					),
					'required'             => array(),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'build_media_alt_caption_review_set' ),
			),
			'npcink-abilities-toolkit/build-media-alt-apply-plan' => array(
				'label'            => __( 'Build Media ALT Apply Plan', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Builds one governed missing-ALT apply plan from an operator-reviewed image without approving, executing, or writing media.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'attachment_id'                     => array( 'type' => 'integer', 'minimum' => 1 ),
						'alt'                               => array( 'type' => 'string', 'minLength' => 3, 'maxLength' => 160 ),
						'expected_current_alt'              => array( 'type' => 'string', 'maxLength' => 160 ),
						'operator_visual_review_confirmed' => array( 'type' => 'boolean' ),
						'review_set_contract'               => array( 'type' => 'string', 'enum' => array( 'media_alt_caption_review_set.v1' ) ),
						'source_item_id'                    => array( 'type' => 'string', 'maxLength' => 190 ),
						'evidence_refs'                     => array( 'type' => 'array', 'maxItems' => 20, 'items' => array( 'type' => 'string', 'maxLength' => 500 ) ),
					),
					'required'             => array( 'attachment_id', 'alt', 'expected_current_alt', 'operator_visual_review_confirmed', 'review_set_contract' ),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'build_media_alt_apply_plan' ),
			),
			'npcink-abilities-toolkit/build-media-settings-reference-repair-plan' => array(
				'label'            => __( 'Build Media Settings Reference Repair Plan', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Scans selected WordPress options and theme mods for hard-coded URLs to a previously replaced media file and builds governed exact replacement actions without mutating settings.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'manage_options',
				'required_scope'   => 'site.read',
				'required_scopes'  => array( 'site.read', 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'attachment_id'              => array( 'type' => 'integer', 'minimum' => 1 ),
						'replacement_id'             => array( 'type' => 'string' ),
						'old_url'                    => array( 'type' => 'string' ),
						'new_url'                    => array( 'type' => 'string' ),
						'old_relative_file'          => array( 'type' => 'string' ),
						'new_relative_file'          => array( 'type' => 'string' ),
						'option_names'               => array( 'type' => 'array', 'maxItems' => 50, 'items' => array( 'type' => 'string' ) ),
						'theme_mod_names'            => array( 'type' => 'array', 'maxItems' => 50, 'items' => array( 'type' => 'string' ) ),
						'include_theme_mods'         => array( 'type' => 'boolean', 'default' => true ),
						'max_settings'               => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 100, 'default' => 50 ),
						'max_replacements_per_setting' => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 20, 'default' => 20 ),
						'excluded_formats'           => array( 'type' => 'array', 'items' => array( 'type' => 'string' ), 'default' => array( 'svg', 'gif', 'ico', 'pdf' ) ),
						'min_width'                  => array( 'type' => 'integer', 'minimum' => 0, 'maximum' => 7680, 'default' => 64 ),
						'min_height'                 => array( 'type' => 'integer', 'minimum' => 0, 'maximum' => 7680, 'default' => 64 ),
						'min_filesize_bytes'         => array( 'type' => 'integer', 'minimum' => 0, 'default' => 0 ),
						'excluded_filename_patterns' => array( 'type' => 'array', 'items' => array( 'type' => 'string' ), 'default' => array( 'logo', 'favicon', 'icon', 'brand', 'payment', 'placeholder' ) ),
					),
					'required'             => array( 'attachment_id' ),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'build_media_settings_reference_repair_plan' ),
			),
			'npcink-abilities-toolkit/get-media-inventory-health' => array(
				'label'            => __( 'Get Media Inventory Health', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Scans a bounded media inventory and summarizes missing alt text, captions, descriptions, source metadata, and format attention.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'mime_type' => array( 'type' => 'string' ),
						'search'    => array( 'type' => 'string' ),
						'per_page'  => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 100, 'default' => 50 ),
						'page'      => array( 'type' => 'integer', 'minimum' => 1, 'default' => 1 ),
					),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array(
							'type'                 => 'object',
							'properties'           => array(
								'total'        => array( 'type' => 'integer' ),
								'page'         => array( 'type' => 'integer' ),
								'per_page'     => array( 'type' => 'integer' ),
								'health_score' => array( 'type' => 'integer' ),
								'issue_counts' => array( 'type' => 'object', 'additionalProperties' => true ),
								'items'        => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
								'summary'      => array( 'type' => 'object', 'additionalProperties' => true ),
							),
							'required'             => array( 'total', 'items', 'summary' ),
							'additionalProperties' => false,
						),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'get_media_inventory_health' ),
			),
			'npcink-abilities-toolkit/inspect-media-asset' => array(
				'label'            => __( 'Inspect Media Asset', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Inspects one attachment file and returns read-only format, size, dimension, and optimization recommendations.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'attachment_id'              => array( 'type' => 'integer', 'minimum' => 1 ),
						'target_max_width'           => array( 'type' => 'integer', 'minimum' => 320, 'maximum' => 7680, 'default' => 1920 ),
						'large_file_threshold_bytes' => array( 'type' => 'integer', 'minimum' => 102400, 'maximum' => 104857600, 'default' => 524288 ),
						'preferred_format'           => array( 'type' => 'string', 'enum' => array( 'webp', 'avif', 'original' ), 'default' => 'webp' ),
					),
					'required'             => array( 'attachment_id' ),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array(
							'type'                 => 'object',
							'properties'           => array(
								'attachment_id'         => array( 'type' => 'integer' ),
								'title'                 => array( 'type' => 'string' ),
								'mime_type'             => array( 'type' => 'string' ),
								'source_format'         => array( 'type' => 'string' ),
								'url'                   => array( 'type' => 'string' ),
								'current_relative_file' => array( 'type' => 'string' ),
								'file_basename'         => array( 'type' => 'string' ),
								'width'                 => array( 'type' => 'integer' ),
								'height'                => array( 'type' => 'integer' ),
								'filesize_bytes'        => array( 'type' => 'integer' ),
								'content_hashes'        => array( 'type' => 'object', 'additionalProperties' => true ),
								'metadata_available'    => array( 'type' => 'boolean' ),
								'storage'               => array( 'type' => 'object', 'additionalProperties' => true ),
								'format_plan'           => array( 'type' => 'object', 'additionalProperties' => true ),
								'warnings'              => array( 'type' => 'array', 'items' => array( 'type' => 'string' ) ),
								'summary'               => array( 'type' => 'object', 'additionalProperties' => true ),
							),
							'required'             => array( 'attachment_id', 'mime_type', 'format_plan', 'warnings', 'summary' ),
							'additionalProperties' => false,
						),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'inspect_media_asset' ),
			),
			'npcink-abilities-toolkit/build-media-derivative-cloud-request' => array(
				'label'            => __( 'Build Media Derivative Cloud Request', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Builds a read-only request contract for a host or Cloud addon to generate an optimized media derivative without uploading, calling Cloud, or mutating WordPress.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'attachment_id'              => array( 'type' => 'integer', 'minimum' => 1 ),
						'target_max_width'           => array( 'type' => 'integer', 'minimum' => 320, 'maximum' => 7680, 'default' => 1920 ),
						'large_file_threshold_bytes' => array( 'type' => 'integer', 'minimum' => 102400, 'maximum' => 104857600, 'default' => 524288 ),
						'preferred_format'           => array( 'type' => 'string', 'enum' => array( 'webp', 'avif', 'jpeg', 'png', 'original' ), 'default' => 'webp' ),
						'quality'                    => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 100, 'default' => 82 ),
						'crop'                       => array(
							'type'                 => 'object',
							'properties'           => array(
								'type'         => array( 'type' => 'string', 'enum' => array( 'aspect_ratio' ), 'default' => 'aspect_ratio' ),
								'aspect_ratio' => array( 'type' => 'string', 'pattern' => '^[1-9][0-9]{0,2}:[1-9][0-9]{0,2}$', 'default' => '16:9' ),
								'position'     => array( 'type' => 'string', 'enum' => array( 'top_left', 'top', 'top_right', 'left', 'center', 'right', 'bottom_left', 'bottom', 'bottom_right' ), 'default' => 'center' ),
							),
							'additionalProperties' => false,
						),
						'watermark'                  => array(
							'type'                 => 'object',
							'properties'           => array(
								'type'          => array( 'type' => 'string', 'enum' => array( 'image', 'text' ), 'default' => 'image' ),
								'artifact_id'   => array( 'type' => 'string' ),
								'text'          => array( 'type' => 'string', 'minLength' => 1, 'maxLength' => 64, 'default' => 'AI' ),
								'position'      => array( 'type' => 'string', 'enum' => array( 'top_left', 'top_right', 'bottom_left', 'bottom_right', 'center' ), 'default' => 'bottom_right' ),
								'opacity'       => array( 'type' => 'number', 'minimum' => 0, 'maximum' => 1, 'default' => 0.75 ),
								'scale_percent' => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 100, 'default' => 18 ),
								'font_size'     => array( 'type' => 'integer', 'minimum' => 8, 'maximum' => 256, 'default' => 48 ),
								'color'         => array( 'type' => 'string', 'default' => '#FFFFFF' ),
								'background'    => array( 'type' => 'string', 'default' => 'rgba(0,0,0,0.35)' ),
								'margin_px'     => array( 'type' => 'integer', 'minimum' => 0, 'maximum' => 1000, 'default' => 24 ),
							),
							'additionalProperties' => false,
						),
					),
					'required'             => array( 'attachment_id' ),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array(
							'type'                 => 'object',
							'properties'           => array(
								'request_contract_version' => array( 'type' => 'string' ),
								'attachment_id'             => array( 'type' => 'integer' ),
								'readonly'                  => array( 'type' => 'boolean' ),
								'storage'                   => array( 'type' => 'object', 'additionalProperties' => true ),
								'blocked'                   => array( 'type' => 'boolean' ),
								'blocked_reason'            => array( 'type' => 'string' ),
								'cloud_job_payload'         => array( 'type' => 'object', 'additionalProperties' => true ),
								'cloud_execution'           => array( 'type' => 'object', 'additionalProperties' => true ),
								'local_adoption'            => array( 'type' => 'object', 'additionalProperties' => true ),
								'risk'                      => array( 'type' => 'object', 'additionalProperties' => true ),
							),
							'required'             => array( 'request_contract_version', 'attachment_id', 'readonly', 'cloud_job_payload', 'cloud_execution', 'local_adoption', 'risk' ),
							'additionalProperties' => true,
						),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
				),
				'execute_callback' => array( $callbacks, 'build_media_derivative_cloud_request' ),
			),
			'npcink-abilities-toolkit/build-media-optimization-plan' => array(
				'label'            => __( 'Build Media Optimization Plan', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Builds a read-only one-attachment optimization plan that combines reviewed media metadata updates with a governed derivative adoption action for one Core approval.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'attachment_id'                  => array( 'type' => 'integer', 'minimum' => 1 ),
						'media_details_input'            => array( 'type' => 'object', 'additionalProperties' => true ),
						'derivative_artifact'            => array( 'type' => 'object', 'additionalProperties' => true ),
						'file_name'                      => array( 'type' => 'string', 'maxLength' => 120 ),
						'expected_current_relative_file' => array( 'type' => 'string' ),
						'expected_current_mime_type'     => array( 'type' => 'string' ),
						'expected_derivative_mime_type'  => array( 'type' => 'string' ),
						'expected_storage_provider'      => array( 'type' => 'string' ),
						'expected_storage_adapter'       => array( 'type' => 'string' ),
						'storage_preflight'              => array(
							'type'                 => 'object',
							'properties'           => array(
								'provider'              => array( 'type' => 'string' ),
								'adapter'               => array( 'type' => 'string' ),
								'attachment_id'         => array( 'type' => 'integer' ),
								'current_relative_file' => array( 'type' => 'string' ),
								'canonical_url'         => array( 'type' => 'string' ),
								'local_file_readable'   => array( 'type' => 'boolean' ),
								'source_read_mode'      => array( 'type' => 'string' ),
								'write_mode'            => array( 'type' => 'string' ),
								'restore_mode'          => array( 'type' => 'string' ),
								'cache_purge_required'  => array( 'type' => 'boolean' ),
								'blocked_reason'        => array( 'type' => 'string' ),
							),
							'additionalProperties' => false,
						),
					),
					'required'             => array( 'attachment_id', 'media_details_input', 'derivative_artifact' ),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'build_media_optimization_plan' ),
			),
			'npcink-abilities-toolkit/build-media-adoption-preflight-summary' => array(
				'label'            => __( 'Build Media Adoption Preflight Summary', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Builds a read-only preflight summary for adopting one reviewed media derivative artifact, including current asset evidence, derivative comparison, bounded content-reference impact, and next-step guidance without mutating WordPress.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read', 'post.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'attachment_id'        => array( 'type' => 'integer', 'minimum' => 1 ),
						'derivative_artifact'  => array( 'type' => 'object', 'additionalProperties' => true ),
						'file_name'            => array( 'type' => 'string', 'maxLength' => 120 ),
						'include_settings_scan' => array( 'type' => 'boolean', 'default' => false ),
					),
					'required'             => array( 'attachment_id' ),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array(
							'type'                 => 'object',
							'properties'           => array(
								'artifact_type'             => array( 'type' => 'string' ),
								'attachment_id'             => array( 'type' => 'integer' ),
								'readonly'                  => array( 'type' => 'boolean' ),
								'direct_wordpress_write'    => array( 'type' => 'boolean' ),
								'proposal_created'          => array( 'type' => 'boolean' ),
								'cloud_call_included'       => array( 'type' => 'boolean' ),
								'current'                   => array( 'type' => 'object', 'additionalProperties' => true ),
								'derivative'                => array( 'type' => 'object', 'additionalProperties' => true ),
								'comparison'                => array( 'type' => 'object', 'additionalProperties' => true ),
								'content_reference_summary' => array( 'type' => 'object', 'additionalProperties' => true ),
								'readiness'                 => array( 'type' => 'object', 'additionalProperties' => true ),
								'next_steps'                => array( 'type' => 'array', 'items' => array( 'type' => 'string' ) ),
							),
							'required'             => array( 'artifact_type', 'attachment_id', 'readonly', 'direct_wordpress_write', 'proposal_created', 'cloud_call_included', 'current', 'derivative', 'comparison', 'content_reference_summary', 'readiness', 'next_steps' ),
							'additionalProperties' => true,
						),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'build_media_adoption_preflight_summary' ),
			),
			'npcink-abilities-toolkit/build-media-rename-plan' => array(
				'label'            => __( 'Build Media Rename Plan', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Builds a read-only one-attachment rename plan for a reviewed target media file name and exact post-content reference updates without mutating WordPress.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read', 'post.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'attachment_id'                  => array( 'type' => 'integer', 'minimum' => 1 ),
						'target_file_name'               => array( 'type' => 'string', 'minLength' => 1, 'maxLength' => 120 ),
						'expected_current_relative_file' => array( 'type' => 'string' ),
						'expected_current_mime_type'     => array( 'type' => 'string' ),
						'expected_current_md5'           => array( 'type' => 'string', 'minLength' => 32, 'maxLength' => 36 ),
							'expected_current_sha256'        => array( 'type' => 'string', 'minLength' => 64, 'maxLength' => 71 ),
							'conflict_mode'                  => array( 'type' => 'string', 'enum' => array( 'fail', 'unique' ), 'default' => 'fail' ),
							'include_reference_updates'      => array( 'type' => 'boolean', 'default' => true ),
							'max_reference_posts'            => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 50, 'default' => 20 ),
							'max_reference_replacements_per_post' => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 20, 'default' => 20 ),
						),
					'required'             => array( 'attachment_id', 'target_file_name' ),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'build_media_rename_plan' ),
			),
			'npcink-abilities-toolkit/build-media-derivative-batch-plan' => array(
				'label'            => __( 'Build Media Derivative Batch Plan', 'npcink-abilities-toolkit' ),
				'description'      => __( 'Builds a bounded read-only plan for batch Cloud media derivative previews from local media filters without calling Cloud, creating proposals, or mutating WordPress.', 'npcink-abilities-toolkit' ),
				'category'         => 'npcink-abilities-toolkit-data',
				'capability'       => 'upload_files',
				'required_scope'   => 'media.read',
				'required_scopes'  => array( 'media.read' ),
				'contract_version' => 'v1',
				'source'           => 'official',
				'input_schema'     => array(
					'type'                 => 'object',
					'properties'           => array(
						'attachment_ids'             => array(
							'type'     => 'array',
							'maxItems' => 100,
							'items'    => array( 'type' => 'integer', 'minimum' => 1 ),
						),
						'mime_type'                  => array( 'type' => 'string', 'default' => 'image' ),
						'search'                     => array( 'type' => 'string' ),
						'date_from'                  => array( 'type' => 'string' ),
						'date_to'                    => array( 'type' => 'string' ),
						'target_format'              => array( 'type' => 'string', 'enum' => array( 'webp', 'avif', 'jpeg', 'png', 'original' ), 'default' => 'webp' ),
						'exclude_formats'            => array(
							'type'    => 'array',
							'default' => array(),
							'items'   => array( 'type' => 'string', 'enum' => array( 'webp', 'avif', 'jpeg', 'jpg', 'png', 'gif', 'svg', 'ico', 'pdf', 'original' ) ),
						),
						'target_max_width'           => array( 'type' => 'integer', 'minimum' => 320, 'maximum' => 7680, 'default' => 1920 ),
						'large_file_threshold_bytes' => array( 'type' => 'integer', 'minimum' => 102400, 'maximum' => 104857600, 'default' => 524288 ),
						'quality'                    => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 100, 'default' => 82 ),
						'crop'                       => array(
							'type'                 => 'object',
							'properties'           => array(
								'type'         => array( 'type' => 'string', 'enum' => array( 'aspect_ratio' ), 'default' => 'aspect_ratio' ),
								'aspect_ratio' => array( 'type' => 'string', 'pattern' => '^[1-9][0-9]{0,2}:[1-9][0-9]{0,2}$', 'default' => '16:9' ),
								'position'     => array( 'type' => 'string', 'enum' => array( 'top_left', 'top', 'top_right', 'left', 'center', 'right', 'bottom_left', 'bottom', 'bottom_right' ), 'default' => 'center' ),
							),
							'additionalProperties' => false,
						),
						'min_width'                  => array( 'type' => 'integer', 'minimum' => 0, 'default' => 0 ),
						'min_height'                 => array( 'type' => 'integer', 'minimum' => 0, 'default' => 0 ),
						'min_filesize_bytes'         => array( 'type' => 'integer', 'minimum' => 0, 'default' => 0 ),
						'max_filesize_bytes'         => array( 'type' => 'integer', 'minimum' => 0, 'default' => 0 ),
						'max_items'                  => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 50, 'default' => 20 ),
						'page'                       => array( 'type' => 'integer', 'minimum' => 1, 'default' => 1 ),
						'watermark'                  => array(
							'type'                 => 'object',
							'properties'           => array(
								'type'          => array( 'type' => 'string', 'enum' => array( 'image', 'text' ), 'default' => 'image' ),
								'artifact_id'   => array( 'type' => 'string' ),
								'text'          => array( 'type' => 'string', 'minLength' => 1, 'maxLength' => 64, 'default' => 'AI' ),
								'position'      => array( 'type' => 'string', 'enum' => array( 'top_left', 'top_right', 'bottom_left', 'bottom_right', 'center' ), 'default' => 'bottom_right' ),
								'opacity'       => array( 'type' => 'number', 'minimum' => 0, 'maximum' => 1, 'default' => 0.75 ),
								'scale_percent' => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 100, 'default' => 18 ),
								'font_size'     => array( 'type' => 'integer', 'minimum' => 8, 'maximum' => 256, 'default' => 48 ),
								'color'         => array( 'type' => 'string', 'default' => '#FFFFFF' ),
								'background'    => array( 'type' => 'string', 'default' => 'rgba(0,0,0,0.35)' ),
								'margin_px'     => array( 'type' => 'integer', 'minimum' => 0, 'maximum' => 1000, 'default' => 24 ),
							),
							'additionalProperties' => false,
						),
					),
					'additionalProperties' => false,
				),
				'output_schema'    => array(
					'type'       => 'object',
					'properties' => array(
						'success' => array( 'type' => 'boolean' ),
						'data'    => array(
							'type'                 => 'object',
							'properties'           => array(
								'plan_contract_version' => array( 'type' => 'string' ),
								'readonly'              => array( 'type' => 'boolean' ),
								'plan_mode'             => array( 'type' => 'string' ),
								'requires_approval'     => array( 'type' => 'boolean' ),
								'commit_execution'      => array( 'type' => 'boolean' ),
								'filters'               => array( 'type' => 'object', 'additionalProperties' => true ),
								'summary'               => array( 'type' => 'object', 'additionalProperties' => true ),
								'eligibility_summary'   => array( 'type' => 'object', 'additionalProperties' => true ),
								'candidates'            => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
								'skipped'               => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
								'blocked_items'         => array( 'type' => 'array', 'items' => array( 'type' => 'object', 'additionalProperties' => true ) ),
								'retryable'             => array( 'type' => 'boolean' ),
								'retry_guidance'        => array( 'type' => 'string' ),
								'operator_next_action'  => array( 'type' => 'string' ),
								'execution_plan'        => array( 'type' => 'object', 'additionalProperties' => true ),
								'boundary'              => array( 'type' => 'object', 'additionalProperties' => true ),
							),
							'required'             => array( 'plan_contract_version', 'readonly', 'plan_mode', 'requires_approval', 'commit_execution', 'summary', 'eligibility_summary', 'candidates', 'skipped', 'blocked_items', 'retryable', 'retry_guidance', 'operator_next_action', 'execution_plan', 'boundary' ),
							'additionalProperties' => true,
						),
						'meta'    => array( 'type' => 'object', 'additionalProperties' => true ),
						'message' => array( 'type' => 'string' ),
					),
					'required'   => array( 'success', 'data' ),
				),
				'execute_callback' => array( $callbacks, 'build_media_derivative_batch_plan' ),
			),
		);
	}
}
