<?php
/**
 * Ordered regression suite part: 50-read-planning-enrichment.
 *
 * Included by tests/run.php; parts must run in the original execution order.
 *
 * @package NpcinkAbilitiesToolkit
 */

use Npcink_Abilities_Toolkit\Integration\Npcink_Catalog_Bridge;
use Npcink_Abilities_Toolkit\Packages\Core_Comment_Pack_Classifier;
use Npcink_Abilities_Toolkit\Packages\Core_Comment_Package;
use Npcink_Abilities_Toolkit\Packages\Core_Destructive_Package;
use Npcink_Abilities_Toolkit\Packages\Core_Read_Pack_Classifier;
use Npcink_Abilities_Toolkit\Packages\Core_Read_Package;
use Npcink_Abilities_Toolkit\Packages\Core_Write_Package;
use Npcink_Abilities_Toolkit\Packages\Read_Definitions\Media_Governance_Read_Definitions;
use Npcink_Abilities_Toolkit\Plugin;
use Npcink_Abilities_Toolkit\Registry\Ability_Registrar;
use Npcink_Abilities_Toolkit\Registry\Annotation_Normalizer;
use Npcink_Abilities_Toolkit\Registry\Category_Registrar;
use Npcink_Abilities_Toolkit\Registry\Contract_Normalizer;
use Npcink_Abilities_Toolkit\Registry\Schema_Normalizer;
use Npcink_Abilities_Toolkit\Rest\Contract_Controller;
use Npcink_Abilities_Toolkit\Security\Permission_Callbacks;
use Npcink_Abilities_Toolkit\Support\Gutenberg_Block_Document;

$media_assets = $core_read_package->build_media_seo_assets(
	array(
		'article' => array( 'title' => 'Article title' ),
		'resolved_image_source' => array(
			'featured' => array(
				'image_origin' => 'ai_generated',
				'prompt' => 'Generated hero prompt',
				'role' => 'featured',
			),
			'inline' => array(
				array(
					'provider_hint' => 'pexels',
					'provider_title' => 'Provider title',
					'section_heading' => 'Inline section',
				),
			),
		),
		'generated_featured_upload' => array(
			'attachment_id' => 88,
			'url' => 'https://example.test/generated.jpg',
			'file_name' => 'generated.jpg',
		),
		'inline_uploads' => array(
			array(
				'attachment_id' => 89,
				'url' => 'https://example.test/inline.jpg',
				'file_name' => 'inline.jpg',
			),
		),
	)
);
npcink_abilities_toolkit_assert_same( true, $media_assets['success'] ?? null, 'build-media-seo-assets returns a success envelope' );
npcink_abilities_toolkit_assert_same( 2, $media_assets['data']['summary']['asset_count'] ?? 0, 'build-media-seo-assets counts featured plus inline assets' );
npcink_abilities_toolkit_assert_same( 'ai_generated', $media_assets['data']['items'][0]['image_origin'] ?? '', 'build-media-seo-assets preserves generated image origin' );
npcink_abilities_toolkit_assert_same( 'ai_generated', $media_assets['data']['items'][0]['source_type'] ?? '', 'build-media-seo-assets maps generated images to ai_generated source type' );
npcink_abilities_toolkit_assert_same( 'AI-generated by site operator', $media_assets['data']['items'][0]['attribution_text'] ?? '', 'build-media-seo-assets adds generated image attribution default' );
npcink_abilities_toolkit_assert_same( 'Generated asset for this site', $media_assets['data']['items'][0]['copyright_notice'] ?? '', 'build-media-seo-assets adds generated image copyright default' );
npcink_abilities_toolkit_assert_same( 'public_free', $media_assets['data']['items'][1]['image_origin'] ?? '', 'build-media-seo-assets infers public-free provider origin' );
npcink_abilities_toolkit_assert_same( 'stock', $media_assets['data']['items'][1]['source_type'] ?? '', 'build-media-seo-assets maps public-free provider images to stock source type' );
$geo_analysis = $core_read_package->geo_analyze(
	array(
		'title' => 'WordPress AI visibility',
		'content' => 'WordPress AI visibility 是什么？It helps answer boxes reuse concise article sections. Teams should add FAQ blocks and direct summaries.',
		'excerpt' => '',
		'focus_keyword' => 'AI visibility',
	)
);
npcink_abilities_toolkit_assert_same( true, $geo_analysis['success'] ?? null, 'geo-analyze returns a success envelope' );
npcink_abilities_toolkit_assert_same( 1, $geo_analysis['data']['summary']['faq_candidate_count'] ?? 0, 'geo-analyze extracts question candidates' );
$optimized_media = $core_read_package->optimize_media_metadata(
	array(
		'article_title' => 'Article title',
		'article_excerpt' => 'Article excerpt',
		'focus_keyword' => 'media SEO',
		'media_assets' => array(
			array(
				'attachment_id' => 90,
				'url' => 'https://example.test/manual.jpg',
				'mime_type' => 'image/jpeg',
				'file_name' => 'manual.jpg',
				'vision_fallback_allowed' => true,
			),
		),
	)
);
npcink_abilities_toolkit_assert_same( true, $optimized_media['success'] ?? null, 'optimize-media-metadata returns a success envelope' );
npcink_abilities_toolkit_assert_same( 1, $optimized_media['data']['summary']['missing_alt_count'] ?? 0, 'optimize-media-metadata counts missing alt text' );
npcink_abilities_toolkit_assert_same( 'owned', $optimized_media['data']['assets'][0]['suggestions']['source_type'] ?? '', 'optimize-media-metadata includes source_type in media detail suggestions' );
npcink_abilities_toolkit_assert_same( 'Owned asset for this site', $optimized_media['data']['assets'][0]['suggestions']['copyright_notice'] ?? '', 'optimize-media-metadata adds owned media copyright default' );
$positioned_blocks = $core_read_package->position_inline_image_blocks(
	array(
		'existing_blocks' => array(
			array(
				'blockName' => 'core/paragraph',
				'attrs' => array(),
				'innerHTML' => '<p>Intro</p>',
				'innerBlocks' => array(),
			),
			array(
				'blockName' => 'core/heading',
				'attrs' => array( 'anchor' => 'target-heading' ),
				'innerHTML' => '<h2>Target heading</h2>',
				'innerBlocks' => array(),
			),
		),
		'inline_blocks' => $inline_blocks['data']['blocks'] ?? array(),
		'inline_plan' => array(
			array(
				'placement_key' => 'alpha-hero',
				'placement' => 'after_heading',
				'section_anchor' => 'target-heading',
				'section_heading' => 'Target heading',
			),
		),
	)
);
npcink_abilities_toolkit_assert_same( true, $positioned_blocks['success'] ?? null, 'position-inline-image-blocks returns a success envelope' );
npcink_abilities_toolkit_assert_same( 1, $positioned_blocks['data']['summary']['positioned_count'] ?? 0, 'position-inline-image-blocks positions matching inline blocks' );
npcink_abilities_toolkit_assert_same( 'core/image', $positioned_blocks['data']['blocks'][2]['blockName'] ?? '', 'position-inline-image-blocks inserts after matching heading' );
$article_production_fingerprint = $core_read_package->build_article_production_fingerprint(
	array(
		'topic'              => 'Local article production',
		'image_mode'         => 'featured_only',
		'publish_mode'       => 'draft',
		'content_format'     => 'html',
		'voice_profile'      => 'practical_editorial',
		'opening_style'      => 'scene',
		'structure_style'    => 'asymmetric',
		'reference_post_ids' => array( 9, 3 ),
	)
);
$article_production_fingerprint_reordered = $core_read_package->build_article_production_fingerprint(
	array(
		'topic'              => 'Local article production',
		'image_mode'         => 'featured_only',
		'publish_mode'       => 'draft',
		'content_format'     => 'html',
		'voice_profile'      => 'practical_editorial',
		'opening_style'      => 'scene',
		'structure_style'    => 'asymmetric',
		'reference_post_ids' => array( 3, 9 ),
	)
);
npcink_abilities_toolkit_assert_same( true, $article_production_fingerprint['success'] ?? null, 'build-article-production-fingerprint returns a success envelope' );
npcink_abilities_toolkit_assert_same( 16, strlen( (string) ( $article_production_fingerprint['data']['production_fingerprint'] ?? '' ) ), 'build-article-production-fingerprint emits a compact 16-character hash' );
npcink_abilities_toolkit_assert_same(
	$article_production_fingerprint['data']['production_fingerprint'] ?? '',
	$article_production_fingerprint_reordered['data']['production_fingerprint'] ?? null,
	'build-article-production-fingerprint sorts reference post ids for stable dedupe'
);
$article_duplicate_check = $core_read_package->check_article_production_duplicate(
	array(
		'production_fingerprint' => (string) ( $article_production_fingerprint['data']['production_fingerprint'] ?? '' ),
		'write_guard_mode'       => 'preserve_manual_edits',
	)
);
npcink_abilities_toolkit_assert_same( true, $article_duplicate_check['success'] ?? null, 'check-article-production-duplicate returns a success envelope' );
npcink_abilities_toolkit_assert_same( false, $article_duplicate_check['data']['duplicate_found'] ?? null, 'check-article-production-duplicate stays readonly when no WordPress lookup is available' );
npcink_abilities_toolkit_assert_same( false, $article_duplicate_check['data']['skip_recommended'] ?? null, 'check-article-production-duplicate does not recommend skipping without a duplicate' );
$GLOBALS['npcink_abilities_toolkit_unit_style_posts'][911] = (object) array(
	'ID'           => 911,
	'post_title'   => 'Fingerprint Duplicate Post',
	'post_status'  => 'draft',
	'post_type'    => 'post',
	'post_excerpt' => '',
	'post_content' => 'Duplicate guard fixture content.',
	'post_name'    => 'fingerprint-duplicate-post',
	'post_author'  => 7,
);
$GLOBALS['npcink_abilities_toolkit_unit_post_meta'][911]['_mai_article_production_fingerprint'] = (string) ( $article_production_fingerprint['data']['production_fingerprint'] ?? '' );
$article_duplicate_found = $core_read_package->check_article_production_duplicate(
	array(
		'production_fingerprint' => (string) ( $article_production_fingerprint['data']['production_fingerprint'] ?? '' ),
	)
);
npcink_abilities_toolkit_assert_same( true, $article_duplicate_found['data']['duplicate_found'] ?? null, 'check-article-production-duplicate finds an editable fingerprint duplicate' );
npcink_abilities_toolkit_assert_same( 911, $article_duplicate_found['data']['duplicate_candidate']['post_id'] ?? null, 'check-article-production-duplicate reports the matched editable post id' );
$GLOBALS['npcink_abilities_toolkit_unit_current_user_caps'] = array( 'edit_post' => false );
$article_duplicate_denied = $core_read_package->check_article_production_duplicate(
	array(
		'production_fingerprint' => (string) ( $article_production_fingerprint['data']['production_fingerprint'] ?? '' ),
	)
);
unset( $GLOBALS['npcink_abilities_toolkit_unit_current_user_caps'] );
npcink_abilities_toolkit_assert_same( false, $article_duplicate_denied['data']['duplicate_found'] ?? null, 'check-article-production-duplicate hides duplicates the caller cannot edit' );
npcink_abilities_toolkit_assert_true( ! isset( $article_duplicate_denied['data']['duplicate_candidate']['post_id'] ), 'check-article-production-duplicate leaks no metadata for uneditable duplicates' );
unset( $GLOBALS['npcink_abilities_toolkit_unit_style_posts'][911], $GLOBALS['npcink_abilities_toolkit_unit_post_meta'][911] );
$article_review_light = $core_read_package->review_article_output_light(
	array(
		'article' => array(
			'content' => implode(
				"\n\n",
				array(
					'<p>首先，AI 写作正在快速发展，因此我们需要全面认识它的优势与不足。</p>',
					'<p>其次，AI 写作可以提高效率，因此企业应该结合实际情况进行合理应用。</p>',
					'<p>最后，AI 写作未来前景广阔，因此团队需要持续优化流程与质量控制。</p>',
					'<p>综上所述，AI 写作具有重要价值，因此我们应当积极拥抱并持续探索。</p>',
				)
			),
		),
		'style_profile' => array(
			'resolved_opening_style' => 'scene',
			'resolved_voice_profile' => 'experiential_editorial',
		),
		'platform_profile' => 'wechat',
		'human_signals' => array(),
		'image_mode' => 'featured_only',
		'media' => array(
			'featured_attached' => true,
		),
	)
);
$article_review_data = is_array( $article_review_light['data'] ?? null ) ? $article_review_light['data'] : array();
$article_ai_risk_review = is_array( $article_review_data['ai_risk_review'] ?? null ) ? $article_review_data['ai_risk_review'] : array();
$article_ai_risk_keys = array();
foreach ( is_array( $article_ai_risk_review['items'] ?? null ) ? $article_ai_risk_review['items'] : array() as $risk_item ) {
	$risk_item = is_array( $risk_item ) ? $risk_item : array();
	$article_ai_risk_keys[] = sanitize_key( (string) ( $risk_item['key'] ?? '' ) );
}
npcink_abilities_toolkit_assert_same( true, $article_review_light['success'] ?? null, 'review-article-output-light returns a success envelope' );
npcink_abilities_toolkit_assert_same( true, $article_review_data['needs_human_review'] ?? null, 'review-article-output-light flags template-heavy output for review' );
npcink_abilities_toolkit_assert_same( 'high', $article_review_data['template_risk_level'] ?? '', 'review-article-output-light preserves high template risk semantics' );
npcink_abilities_toolkit_assert_true( in_array( 'human_signal_gap', $article_ai_risk_keys, true ), 'review-article-output-light reports missing human signal risk' );
npcink_abilities_toolkit_assert_true( in_array( 'evidence_gap', $article_ai_risk_keys, true ), 'review-article-output-light reports missing evidence risk' );
$reference_style_review = $core_read_package->review_article_output_light(
	array(
		'article' => array(
			'content' => "<p>最近我们在一次编辑复盘里突然意识到，文章一旦写得太顺，反而像机器。</p>\n\n<p>我后来会故意先把现场判断扔出来，再补背景，因为团队实操和踩坑本来就不是教科书顺序。</p>\n\n<p>我们照着这个节奏改完以后，内容没那么完美，但至少终于像人写的了。</p>",
		),
		'style_profile' => array(
			'resolved_opening_style' => 'scene',
			'resolved_voice_profile' => 'experiential_editorial',
		),
		'image_mode' => 'featured_only',
		'media' => array(
			'featured_attached' => true,
		),
	)
);
npcink_abilities_toolkit_assert_same( false, $reference_style_review['data']['needs_human_review'] ?? null, 'review-article-output-light relaxes missing evidence risks when reference style strongly matches' );
npcink_abilities_toolkit_assert_same( 'ready_for_editorial_review', $reference_style_review['data']['next_action'] ?? '', 'review-article-output-light keeps matching reference-style output reviewable' );
$production_result = $core_read_package->compose_article_production_result(
	array(
		'input' => array(
			'topic'              => 'Local article production',
			'image_mode'         => 'featured_and_inline',
			'publish_mode'       => 'draft',
			'reference_post_ids' => array( 9, 3 ),
			'write_guard_mode'   => 'preserve_manual_edits',
		),
		'draft' => array(
			'post_id'      => 99,
			'edit_link'    => 'https://example.test/edit/99',
			'preview_link' => 'https://example.test/preview/99',
			'public_link'  => 'https://example.test/article/99',
		),
		'media' => array(
			'featured_attached' => true,
			'position_inline_image_blocks' => array(
				'summary' => array(
					'positioned_count' => 1,
					'appended_count'   => 1,
				),
			),
		),
		'review' => array(
			'writing_naturalness'   => 70,
			'style_match_score'     => 94,
			'image_relevance_score' => 82,
			'needs_human_review'    => false,
			'next_action'           => 'needs_layout_review',
			'template_risk_level'   => 'medium',
			'signals'               => array(
				'anti_template_findings' => array( '段落层次偏少，容易显得像模板摘要。' ),
				'style_findings'         => array(),
			),
		),
		'duplicate_guard' => array(
			'production_fingerprint' => 'abc123def4567890',
			'duplicate_found'        => true,
			'skip_recommended'       => true,
			'summary_text'           => '检测到同指纹文章 #88《已有草稿》，建议先复核现有稿件。',
			'duplicate_candidate'    => array(
				'post_id' => 88,
				'title'   => '已有草稿',
			),
		),
	)
);
$production_data = is_array( $production_result['data'] ?? null ) ? $production_result['data'] : array();
npcink_abilities_toolkit_assert_same( true, $production_result['success'] ?? null, 'compose-article-production-result returns a success envelope' );
npcink_abilities_toolkit_assert_same( 'degraded', $production_data['result_mode'] ?? '', 'compose-article-production-result exposes degraded result semantics' );
npcink_abilities_toolkit_assert_true( in_array( 'inline_position_partial_fallback', (array) ( $production_data['degraded_reasons'] ?? array() ), true ), 'compose-article-production-result preserves inline fallback degradation' );
npcink_abilities_toolkit_assert_true( in_array( 'duplicate_production_candidate', (array) ( $production_data['degraded_reasons'] ?? array() ), true ), 'compose-article-production-result preserves duplicate guard degradation' );
npcink_abilities_toolkit_assert_same( 'abc123def4567890', $production_data['production_fingerprint'] ?? '', 'compose-article-production-result preserves duplicate fingerprint' );
npcink_abilities_toolkit_assert_same( true, $production_data['skip_recommended'] ?? null, 'compose-article-production-result preserves duplicate skip recommendation' );
npcink_abilities_toolkit_assert_true( in_array( 'duplicate_candidate_detected', (array) ( $production_data['completed_stages'] ?? array() ), true ), 'compose-article-production-result records duplicate candidate stage' );
npcink_abilities_toolkit_assert_true( false !== strpos( (string) ( $production_data['summary_text'] ?? '' ), '检测到可复用旧稿' ), 'compose-article-production-result summarizes duplicate reuse handoff' );
$production_result_fallback = $core_read_package->compose_article_production_result(
	array(
		'input' => array(
			'topic'              => 'Local article production',
			'image_mode'         => 'featured_only',
			'publish_mode'       => 'draft',
			'content_format'     => 'html',
			'voice_profile'      => 'practical_editorial',
			'opening_style'      => 'scene',
			'structure_style'    => 'asymmetric',
			'reference_post_ids' => array( 3, 9 ),
		),
	)
);
npcink_abilities_toolkit_assert_same(
	(string) ( $article_production_fingerprint['data']['production_fingerprint'] ?? '' ),
	(string) ( $production_result_fallback['data']['production_fingerprint'] ?? '' ),
	'compose-article-production-result fills a stable fingerprint when duplicate guard omits one'
);
$GLOBALS['npcink_abilities_toolkit_unit_style_posts'] = array(
	11 => (object) array(
		'ID'           => 11,
		'post_author'  => 7,
		'post_title'   => '现场复盘',
		'post_content' => "<p>最近我们在一次编辑复盘里发现，开头先放现场判断更自然。</p>\n\n<p>我和团队实操时会保留一点踩坑细节，让文章不像模板。</p>\n\n<p>下一步建议继续保留这种判断节奏。</p>",
	),
	12 => (object) array(
		'ID'           => 12,
		'post_author'  => 7,
		'post_title'   => '团队笔记',
		'post_content' => "<p>在一次上线后，我们把数据指标和人工判断放在一起看。</p>\n\n<p>团队实操中最有价值的是先说取舍，再补背景。</p>\n\n<p>可以把这种写法沉淀成编辑基线。</p>",
	),
	13 => (object) array(
		'ID'           => 13,
		'post_author'  => 3,
		'post_title'   => '站点样本',
		'post_content' => "<p>如果只看单篇文章，很容易误判站点风格。</p>\n\n<p>把最近内容合起来看，结构和语气会更稳定。</p>\n\n<p>总的来说，基线应该轻量而可复用。</p>",
	),
);
$GLOBALS['npcink_abilities_toolkit_unit_transients'] = array();
$reference_style = $core_read_package->extract_reference_post_style(
	array(
		'reference_post_ids' => array( 11, 12 ),
	)
);
npcink_abilities_toolkit_assert_same( true, $reference_style['success'] ?? null, 'extract-reference-post-style returns a success envelope' );
npcink_abilities_toolkit_assert_same( 2, $reference_style['data']['profile']['sample_count'] ?? null, 'extract-reference-post-style profiles two reference samples' );
npcink_abilities_toolkit_assert_same( 'scene', $reference_style['data']['profile']['dominant_opening_style'] ?? '', 'extract-reference-post-style detects scene-led openings' );
npcink_abilities_toolkit_assert_same( 'action', $reference_style['data']['profile']['dominant_ending_style'] ?? '', 'extract-reference-post-style detects action endings' );
npcink_abilities_toolkit_assert_true( false !== strpos( (string) ( $reference_style['data']['profile']['style_brief'] ?? '' ), '段落平均长度约' ), 'extract-reference-post-style returns a compact style brief' );
$GLOBALS['npcink_abilities_toolkit_unit_transients'] = array();
$author_baseline = $core_read_package->extract_style_baseline(
	array(
		'mode'      => 'author_recent',
		'author_id' => 7,
		'limit'     => 4,
	)
);
npcink_abilities_toolkit_assert_same( true, $author_baseline['success'] ?? null, 'extract-style-baseline returns a success envelope' );
npcink_abilities_toolkit_assert_same( 'author_recent', $author_baseline['data']['source'] ?? '', 'extract-style-baseline keeps author source when author samples exist' );
npcink_abilities_toolkit_assert_same( 2, $author_baseline['data']['profile']['sample_count'] ?? null, 'extract-style-baseline profiles author samples' );
$GLOBALS['npcink_abilities_toolkit_unit_transients'] = array();
$site_baseline = $core_read_package->extract_style_baseline(
	array(
		'mode'  => 'site_recent',
		'limit' => 3,
	)
);
npcink_abilities_toolkit_assert_same( 'site_recent', $site_baseline['data']['source'] ?? '', 'extract-style-baseline keeps site source for site baselines' );
npcink_abilities_toolkit_assert_same( 3, $site_baseline['data']['profile']['sample_count'] ?? null, 'extract-style-baseline profiles site samples' );
$optimization_report = $core_read_package->build_article_optimization_report(
	array(
		'post'           => array(
			'id'        => 42,
			'title'     => 'Optimization target',
			'status'    => 'publish',
			'edit_link' => 'https://example.test/wp-admin/post.php?post=42&action=edit',
		),
		'seo'            => array(
			'recommendations' => array(
				array(
					'type'     => 'keyword',
					'priority' => 'high',
					'title'    => '补焦点关键词',
					'detail'   => '首段补齐关键词。',
				),
			),
		),
		'geo'            => array(
			'recommendations' => array(
				array(
					'type'     => 'answerability',
					'priority' => 'medium',
					'title'    => '补答案摘要',
					'detail'   => '增加 answer-first 段落。',
				),
			),
		),
		'internal_links' => array(
			'placement_plan' => array(
				array(
					'anchor_text' => '内部链接锚点',
					'reason'      => '连接相关旧文。',
				),
			),
		),
		'media'          => array(
			'assets' => array(
				array(
					'issues' => array( '缺少 alt', '缺少 caption' ),
				),
			),
		),
	)
);
npcink_abilities_toolkit_assert_same( true, $optimization_report['success'] ?? null, 'build-article-optimization-report returns a success envelope' );
npcink_abilities_toolkit_assert_same( 42, $optimization_report['data']['post']['post_id'] ?? null, 'build-article-optimization-report normalizes post id' );
npcink_abilities_toolkit_assert_same( 'needs_attention', $optimization_report['data']['summary']['status'] ?? '', 'build-article-optimization-report marks high-priority reports for attention' );
npcink_abilities_toolkit_assert_same( 4, $optimization_report['data']['summary']['total_recommendations'] ?? null, 'build-article-optimization-report merges SEO, GEO, internal link, and media recommendations' );
$seo_report_context = $core_read_package->build_seo_report_context(
	array(
		'input'         => '<p>这是一段偏短的正文，用来触发内容深度建议。</p>',
		'focus_keyword' => '本地能力包',
	)
);
npcink_abilities_toolkit_assert_same( true, $seo_report_context['success'] ?? null, 'seo-report-context returns a success envelope' );
npcink_abilities_toolkit_assert_same( 'local_seo_report_context', $seo_report_context['meta']['source'] ?? '', 'seo-report-context records deterministic source metadata' );
npcink_abilities_toolkit_assert_same( 1, $seo_report_context['data']['summary']['high_priority_count'] ?? null, 'seo-report-context counts missing focus keyword as high priority' );
npcink_abilities_toolkit_assert_true( 88 > (int) ( $seo_report_context['data']['score'] ?? 88 ), 'seo-report-context lowers score when checks fail' );
$GLOBALS['npcink_abilities_toolkit_unit_style_posts'][77] = (object) array(
	'ID'           => 77,
	'post_title'   => 'Optimization Context Post',
	'post_status'  => 'draft',
	'post_type'    => 'post',
	'post_excerpt' => '',
	'post_content' => 'Optimization context content.',
	'post_name'    => 'optimization-context-post',
);
$post_context = $core_read_package->read_post_optimization_context(
	array(
		'post_id' => 77,
	)
);
npcink_abilities_toolkit_assert_same( true, $post_context['success'] ?? null, 'read-post-optimization-context returns a success envelope' );
npcink_abilities_toolkit_assert_same( 77, $post_context['data']['id'] ?? null, 'read-post-optimization-context reads the requested post id' );
npcink_abilities_toolkit_assert_same( 'optimization-context-post', $post_context['data']['slug'] ?? '', 'read-post-optimization-context exposes slug for optimization workflows' );
npcink_abilities_toolkit_assert_same( 'standard', $post_context['data']['format'] ?? '', 'read-post-optimization-context defaults empty post format to standard' );
$GLOBALS['npcink_abilities_toolkit_unit_post_meta'][77]['_yoast_wpseo_title'] = 'Optimization SEO Title';
$GLOBALS['npcink_abilities_toolkit_unit_post_meta'][77]['_yoast_wpseo_metadesc'] = 'Optimization SEO Description';
$agent_post_context = $core_read_package->get_post_context(
	array(
		'post_id'      => 77,
		'include_meta' => true,
		'meta_keys'    => array( '_yoast_wpseo_title' ),
	)
);
npcink_abilities_toolkit_assert_same( true, $agent_post_context['success'] ?? null, 'get-post-context returns a success envelope' );
npcink_abilities_toolkit_assert_same( 77, $agent_post_context['data']['post']['id'] ?? null, 'get-post-context reads the requested post id' );
npcink_abilities_toolkit_assert_same( 'Optimization context content.', $agent_post_context['data']['post']['content'] ?? '', 'get-post-context includes post content by default' );
npcink_abilities_toolkit_assert_same( 1, $agent_post_context['data']['stats']['block_count'] ?? null, 'get-post-context falls back to a freeform block for plain content' );
	npcink_abilities_toolkit_assert_same( 'Optimization SEO Title', $agent_post_context['data']['meta']['_yoast_wpseo_title'] ?? '', 'get-post-context supports scoped metadata reads' );
	$GLOBALS['npcink_abilities_toolkit_unit_post_meta'][77]['_vendor_api_token'] = 'tok-super-secret';
	$unscoped_agent_post_context = $core_read_package->get_post_context(
		array(
			'post_id'      => 77,
			'include_meta' => true,
		)
	);
	npcink_abilities_toolkit_assert_true( ! isset( $unscoped_agent_post_context['data']['meta']['_vendor_api_token'] ), 'get-post-context never returns all metadata when no safe keys are supplied' );
	$blocked_post_meta = $core_read_package->get_post_meta(
		array(
			'post_id'  => 77,
			'meta_key' => '_vendor_api_token',
		)
	);
	npcink_abilities_toolkit_assert_true( is_wp_error( $blocked_post_meta ), 'get-post-meta blocks sensitive metadata keys' );
	npcink_abilities_toolkit_assert_same( 'npcink_abilities_toolkit_meta_key_blocked', $blocked_post_meta->get_error_code() ?? '', 'get-post-meta uses a stable sensitive-key error code' );
	$missing_post_meta_key = $core_read_package->get_post_meta( array( 'post_id' => 77 ) );
	npcink_abilities_toolkit_assert_true( is_wp_error( $missing_post_meta_key ), 'get-post-meta requires one explicit safe key' );
	npcink_abilities_toolkit_assert_same( 'npcink_abilities_toolkit_meta_key_required', $missing_post_meta_key->get_error_code() ?? '', 'get-post-meta uses a stable missing-key error code' );
	$safe_post_meta = $core_read_package->get_post_meta(
		array(
			'post_id'  => 77,
			'meta_key' => '_yoast_wpseo_title',
		)
	);
	npcink_abilities_toolkit_assert_same( 'Optimization SEO Title', $safe_post_meta['value'] ?? '', 'get-post-meta returns an explicitly requested safe key' );
$publishing_checklist = $core_read_package->get_content_publishing_checklist(
	array(
		'post_id' => 77,
	)
);
npcink_abilities_toolkit_assert_same( true, $publishing_checklist['success'] ?? null, 'get-content-publishing-checklist returns a success envelope' );
npcink_abilities_toolkit_assert_same( false, $publishing_checklist['data']['ready'] ?? null, 'get-content-publishing-checklist blocks thin content from ready state' );
npcink_abilities_toolkit_assert_true( in_array( 'content', $publishing_checklist['data']['missing'] ?? array(), true ), 'get-content-publishing-checklist reports missing content depth' );
npcink_abilities_toolkit_assert_true( in_array( 'excerpt', $publishing_checklist['data']['warnings'] ?? array(), true ), 'get-content-publishing-checklist reports missing excerpt as warning' );
$GLOBALS['npcink_abilities_toolkit_unit_style_posts'][78] = (object) array(
	'ID'           => 78,
	'post_title'   => 'Internal Link Candidate',
	'post_status'  => 'publish',
	'post_type'    => 'post',
	'post_excerpt' => 'Candidate excerpt.',
	'post_content' => 'Optimization workflow candidate content with enough body text to support an internal link opportunity report for related workflow articles.',
	'post_name'    => 'internal-link-candidate',
	'post_author'  => 7,
	'post_modified' => '2024-01-02 03:04:05',
);
$inventory_health = $core_read_package->get_content_inventory_health(
	array(
		'post_type' => 'post',
		'status'    => 'any',
		'per_page'  => 5,
		'page'      => 1,
	)
);
npcink_abilities_toolkit_assert_same( true, $inventory_health['success'] ?? null, 'get-content-inventory-health returns a success envelope' );
npcink_abilities_toolkit_assert_true( (int) ( $inventory_health['data']['summary']['scanned_count'] ?? 0 ) > 0, 'get-content-inventory-health scans bounded inventory rows' );
npcink_abilities_toolkit_assert_true( isset( $inventory_health['data']['health_score'] ), 'get-content-inventory-health returns a health score' );
$inventory_health_cached = $core_read_package->get_content_inventory_health(
	array(
		'post_type' => 'post',
		'status'    => 'any',
		'per_page'  => 5,
		'page'      => 1,
	)
);
npcink_abilities_toolkit_assert_same( true, $inventory_health_cached['meta']['cache_hit'] ?? null, 'get-content-inventory-health uses the bounded read cache on repeated calls' );
$GLOBALS['npcink_abilities_toolkit_unit_style_posts'][79] = (object) array(
	'ID'           => 79,
	'post_title'   => 'Core Governance Comment Smoke',
	'post_status'  => 'draft',
	'post_type'    => 'post',
	'post_excerpt' => '',
	'post_content' => 'Temporary smoke content for local validation.',
	'post_name'    => 'core-governance-comment-smoke',
	'post_author'  => 7,
	'post_modified' => '2026-05-30 10:00:00',
);
$test_inventory = $core_read_package->get_nonproduction_content_inventory(
	array(
		'patterns' => array( 'Core Governance' ),
		'per_page' => 10,
	)
);
npcink_abilities_toolkit_assert_same( true, $test_inventory['success'] ?? null, 'get-nonproduction-content-inventory returns a success envelope' );
npcink_abilities_toolkit_assert_same( true, $test_inventory['data']['detected'] ?? null, 'get-nonproduction-content-inventory detects matching smoke content' );
npcink_abilities_toolkit_assert_same( 'Core Governance', $test_inventory['data']['posts']['items'][0]['matched_pattern'] ?? '', 'get-nonproduction-content-inventory returns matched pattern' );
$GLOBALS['npcink_abilities_toolkit_unit_style_posts'][81] = (object) array(
	'ID'           => 81,
	'post_title'   => 'Core Plan Bridge Content Candidate',
	'post_status'  => 'draft',
	'post_type'    => 'post',
	'post_excerpt' => '',
	'post_content' => 'Temporary plan bridge fixture content for local validation.',
	'post_name'    => 'core-plan-bridge-content-candidate',
	'post_author'  => 7,
	'post_modified' => '2026-05-30 10:30:00',
);
$default_test_inventory = $core_read_package->get_nonproduction_content_inventory(
	array(
		'per_page' => 10,
	)
);
$default_plan_bridge_match = null;
foreach ( (array) ( $default_test_inventory['data']['posts']['items'] ?? array() ) as $default_test_inventory_item ) {
	if ( 81 === (int) ( $default_test_inventory_item['post_id'] ?? 0 ) ) {
		$default_plan_bridge_match = $default_test_inventory_item;
		break;
	}
}
npcink_abilities_toolkit_assert_same( true, $default_test_inventory['data']['detected'] ?? null, 'get-nonproduction-content-inventory detects Core Plan Bridge fixtures by default' );
npcink_abilities_toolkit_assert_same( 'core plan bridge content candidate', $default_plan_bridge_match['matched_pattern'] ?? '', 'get-nonproduction-content-inventory includes Core Plan Bridge fixture patterns by default' );
$cleanup_plan = $core_read_package->build_nonproduction_content_cleanup_plan(
	array(
		'patterns'    => array( 'Core Governance' ),
		'max_actions' => 5,
	)
);
npcink_abilities_toolkit_assert_same( true, $cleanup_plan['success'] ?? null, 'build-nonproduction-content-cleanup-plan returns a success envelope' );
npcink_abilities_toolkit_assert_same( 'batch', $cleanup_plan['data']['proposal_mode'] ?? '', 'nonproduction content cleanup plan requests batch proposal intake' );
npcink_abilities_toolkit_assert_same( true, $cleanup_plan['data']['batch_approval'] ?? null, 'nonproduction content cleanup plan requests one approval for the generated action batch' );
npcink_abilities_toolkit_assert_same( 'npcink-abilities-toolkit/trash-post', $cleanup_plan['data']['write_actions'][0]['target_ability_id'] ?? '', 'nonproduction content cleanup plan reuses trash-post' );
npcink_abilities_toolkit_assert_same( false, $cleanup_plan['data']['write_actions'][0]['commit_execution'] ?? null, 'nonproduction content cleanup plan does not execute commits' );
$default_cleanup_plan = $core_read_package->build_nonproduction_content_cleanup_plan(
	array(
		'max_actions' => 5,
	)
);
$default_cleanup_plan_bridge_action = null;
foreach ( (array) ( $default_cleanup_plan['data']['write_actions'] ?? array() ) as $default_cleanup_action ) {
	if ( 81 === (int) ( $default_cleanup_action['input']['post_id'] ?? 0 ) ) {
		$default_cleanup_plan_bridge_action = $default_cleanup_action;
		break;
	}
}
npcink_abilities_toolkit_assert_same( 'npcink-abilities-toolkit/trash-post', $default_cleanup_plan_bridge_action['target_ability_id'] ?? '', 'nonproduction content cleanup plan includes Core Plan Bridge fixture posts by default' );
$terms_only_cleanup_plan = $core_read_package->build_nonproduction_content_cleanup_plan(
	array(
		'include_posts'    => false,
		'include_terms'    => false,
		'include_comments' => false,
		'max_actions'      => 5,
	)
);
npcink_abilities_toolkit_assert_same( 0, count( (array) ( $terms_only_cleanup_plan['data']['preview']['posts'] ?? array() ) ), 'nonproduction content cleanup plan honors include_posts=false' );
npcink_abilities_toolkit_assert_same( 0, count( (array) ( $terms_only_cleanup_plan['data']['write_actions'] ?? array() ) ), 'nonproduction content cleanup plan does not generate post actions when include_posts=false' );
$GLOBALS['npcink_abilities_toolkit_unit_style_posts'][80] = (object) array(
	'ID'           => 80,
	'post_title'   => 'Inventory Fix Candidate',
	'post_status'  => 'draft',
	'post_type'    => 'post',
	'post_excerpt' => '',
	'post_content' => 'Inventory fix candidate content with enough text to generate a deterministic excerpt and metadata description for review planning.',
	'post_name'    => '',
	'post_author'  => 7,
	'post_modified' => '2026-05-30 11:00:00',
);
$content_fix_plan = $core_read_package->build_content_inventory_fix_plan(
	array(
		'post_ids'    => array( 80 ),
		'issue_types' => array( 'seo_title', 'seo_description', 'slug', 'excerpt' ),
	)
);
npcink_abilities_toolkit_assert_same( true, $content_fix_plan['success'] ?? null, 'build-content-inventory-fix-plan returns a success envelope' );
npcink_abilities_toolkit_assert_same( true, $content_fix_plan['data']['requires_approval'] ?? null, 'content inventory fix plan requires approval' );
npcink_abilities_toolkit_assert_same( 'npcink-abilities-toolkit/set-post-seo-meta', $content_fix_plan['data']['write_actions'][0]['target_ability_id'] ?? '', 'content inventory fix plan reuses SEO write ability' );
npcink_abilities_toolkit_assert_same( false, $content_fix_plan['data']['write_actions'][0]['commit_execution'] ?? null, 'content inventory fix plan does not execute commits' );
npcink_abilities_toolkit_assert_true( isset( $content_fix_plan['data']['preview'][0]['before']['seo_title'] ), 'content inventory fix plan returns before preview' );
npcink_abilities_toolkit_assert_true( isset( $content_fix_plan['data']['preview'][0]['after_suggestion']['seo_title'] ), 'content inventory fix plan returns after suggestion preview' );
$GLOBALS['npcink_abilities_toolkit_unit_style_posts'][81] = (object) array(
	'ID'           => 81,
	'post_title'   => '',
	'post_status'  => 'draft',
	'post_type'    => 'post',
	'post_excerpt' => 'Has excerpt.',
	'post_content' => 'Inventory fix title candidate content with enough words to avoid unrelated body content warnings during planning.',
	'post_name'    => 'inventory-fix-title-candidate',
	'post_author'  => 7,
	'post_modified' => '2026-05-30 11:10:00',
);
$title_fix_plan = $core_read_package->build_content_inventory_fix_plan(
	array(
		'post_ids'    => array( 81 ),
		'issue_types' => array( 'title' ),
	)
);
npcink_abilities_toolkit_assert_same( 'npcink-abilities-toolkit/update-post', $title_fix_plan['data']['write_actions'][0]['target_ability_id'] ?? '', 'content inventory fix plan maps missing title to update-post' );
npcink_abilities_toolkit_assert_same( array( 'title' ), $title_fix_plan['data']['write_actions'][0]['requires_input'] ?? array(), 'content inventory title plan requires a reviewed title input' );
$bulk_checklist = $core_read_package->get_bulk_publishing_checklist(
	array(
		'post_ids' => array( 77, 78, 77 ),
	)
);
npcink_abilities_toolkit_assert_same( true, $bulk_checklist['success'] ?? null, 'get-bulk-publishing-checklist returns a success envelope' );
npcink_abilities_toolkit_assert_same( 2, $bulk_checklist['data']['total'] ?? null, 'get-bulk-publishing-checklist deduplicates post ids' );
npcink_abilities_toolkit_assert_true( (int) ( $bulk_checklist['data']['blocked_count'] ?? 0 ) >= 1, 'get-bulk-publishing-checklist counts blocked posts' );
$internal_link_report = $core_read_package->get_internal_link_opportunity_report(
	array(
		'post_id'       => 77,
		'focus_keyword' => 'workflow',
		'max_targets'   => 3,
	)
);
npcink_abilities_toolkit_assert_same( true, $internal_link_report['success'] ?? null, 'get-internal-link-opportunity-report returns a success envelope' );
npcink_abilities_toolkit_assert_same( 77, $internal_link_report['data']['source_post']['post_id'] ?? null, 'get-internal-link-opportunity-report keeps source post id' );
npcink_abilities_toolkit_assert_true( (int) ( $internal_link_report['data']['summary']['candidate_count'] ?? 0 ) >= 1, 'get-internal-link-opportunity-report finds local candidate posts in isolated tests' );
$internal_link_candidates = $core_read_package->resolve_internal_link_targets(
	array(
		'current_post_id'           => 77,
		'post_type'                 => 'post',
		'title'                     => 'Workflow optimization guide',
		'content_text'              => 'Workflow optimization article body that needs related internal reading.',
		'selected_text'             => 'workflow optimization',
		'content_blocks'            => array(
			array( 'client_id' => 'block-workflow', 'block_name' => 'core/paragraph', 'text' => 'This workflow optimization pattern improves internal navigation.' ),
		),
		'query'                     => 'workflow',
		'candidate_limit'           => 4,
		'max_targets'               => 3,
		'related_content_evidence'  => array(
			array(
				'post_id'      => 77,
				'title'        => 'Current post must be excluded',
				'url'          => 'https://example.test/current',
				'evidence_ref' => 'site_knowledge:current',
			),
			array(
				'post_id'      => 280976,
				'title'        => 'Supplied related workflow target',
				'url'          => 'https://example.test/supplied-workflow',
				'score'        => 0.82,
				'evidence_ref' => 'site_knowledge:supplied_workflow',
				'incoming_count' => 0,
				'link_graph_issues' => array( 'orphan_post' ),
				'shared_terms' => array( 'workflow' ),
				'graph_evidence_available' => true,
			),
		),
	)
);
npcink_abilities_toolkit_assert_same( true, $internal_link_candidates['success'] ?? null, 'resolve-internal-link-targets returns a success envelope' );
npcink_abilities_toolkit_assert_same( 'internal_link_candidates.v1', $internal_link_candidates['data']['internal_link_candidates']['artifact_type'] ?? '', 'resolve-internal-link-targets returns reusable internal-link candidate artifact' );
npcink_abilities_toolkit_assert_same( 'native_editor_commit', $internal_link_candidates['data']['internal_link_candidates']['final_write_path'] ?? '', 'resolve-internal-link-targets permits only a visible editor-state commit' );
npcink_abilities_toolkit_assert_same( false, $internal_link_candidates['data']['internal_link_candidates']['direct_wordpress_write'] ?? null, 'resolve-internal-link-targets does not perform WordPress writes' );
npcink_abilities_toolkit_assert_true( (int) ( $internal_link_candidates['data']['summary']['candidate_count'] ?? 0 ) >= 1, 'resolve-internal-link-targets builds bounded candidate rows' );
npcink_abilities_toolkit_assert_true( in_array( 'supplied_related_content_evidence', array_column( $internal_link_candidates['data']['internal_link_candidates']['items'] ?? array(), 'source' ), true ), 'resolve-internal-link-targets can include host-supplied related content evidence without owning that provider' );
npcink_abilities_toolkit_assert_true( ! in_array( 77, array_column( $internal_link_candidates['data']['internal_link_candidates']['items'] ?? array(), 'target_post_id' ), true ), 'resolve-internal-link-targets excludes the current post from candidates' );
$prioritized_internal_link = $internal_link_candidates['data']['internal_link_candidates']['items'][0] ?? array();
npcink_abilities_toolkit_assert_same( 280976, $prioritized_internal_link['target_post_id'] ?? 0, 'resolve-internal-link-targets gives a bounded priority boost to an orphaned related target' );
npcink_abilities_toolkit_assert_true( in_array( 'orphan_post', $prioritized_internal_link['link_graph_issues'] ?? array(), true ), 'resolve-internal-link-targets preserves local graph evidence for operator review' );
npcink_abilities_toolkit_assert_same( array( 'workflow' ), $prioritized_internal_link['shared_terms'] ?? array(), 'resolve-internal-link-targets preserves bounded topic-cluster evidence' );
$matched_internal_links = array_values( array_filter( $internal_link_candidates['data']['internal_link_candidates']['items'] ?? array(), static fn( $item ) => ! empty( $item['source_match'] ) ) );
npcink_abilities_toolkit_assert_same( 'block-workflow', $matched_internal_links[0]['source_match']['block_client_id'] ?? '', 'resolve-internal-link-targets locates an exact existing editor phrase' );
npcink_abilities_toolkit_assert_same( 'workflow optimization', $matched_internal_links[0]['suggested_anchor_text'] ?? '', 'resolve-internal-link-targets uses the exact article phrase as the reviewed anchor' );
npcink_abilities_toolkit_assert_same( 'supplied_evidence', $matched_internal_links[0]['candidate_source'] ?? '', 'resolve-internal-link-targets labels supplied semantic evidence separately from local fallback' );
$mixed_anchor_result = $core_read_package->resolve_internal_link_targets(
	array(
		'current_post_id' => 77,
		'content_blocks'  => array(
			array(
				'client_id' => 'block-mixed-anchor',
				'block_name' => 'core/paragraph',
				'text' => '两小时极速搭建WordPress个人博客 – WordPress教程',
			),
		),
		'related_content_evidence' => array(
			array(
				'post_id' => 280977,
				'title' => '两小时极速搭建WordPress个人博客 – WordPress教程',
				'url' => 'https://example.test/mixed-anchor',
			),
		),
	)
);
$mixed_anchor_item = $mixed_anchor_result['data']['internal_link_candidates']['items'][0] ?? array();
npcink_abilities_toolkit_assert_same( '两小时极速搭建WordPress个人博客 – WordPress教程', $mixed_anchor_item['suggested_anchor_text'] ?? '', 'resolve-internal-link-targets preserves a complete mixed Chinese/ASCII title anchor' );
npcink_abilities_toolkit_assert_true( 1 !== preg_match( '/(?:Wo|WordPres)$/', (string) ( $mixed_anchor_item['suggested_anchor_text'] ?? '' ) ), 'resolve-internal-link-targets never ends a title anchor inside an ASCII word' );
$long_mixed_title = str_repeat( '中', 75 ) . 'WordPress教程';
$long_mixed_result = $core_read_package->resolve_internal_link_targets(
	array(
		'current_post_id' => 77,
		'content_blocks'  => array( array( 'client_id' => 'block-long-mixed', 'block_name' => 'core/paragraph', 'text' => $long_mixed_title ) ),
		'related_content_evidence' => array( array( 'post_id' => 280978, 'title' => $long_mixed_title, 'url' => 'https://example.test/long-mixed-anchor' ) ),
	)
);
$long_mixed_anchor = (string) ( $long_mixed_result['data']['internal_link_candidates']['items'][0]['suggested_anchor_text'] ?? '' );
npcink_abilities_toolkit_assert_true( $long_mixed_anchor !== '' && 1 !== preg_match( '/[A-Za-z0-9]$/', $long_mixed_anchor ), 'resolve-internal-link-targets backs up before an ASCII word when the title limit falls inside that word' );
$heading_match_result = $core_read_package->resolve_internal_link_targets(
	array(
		'current_post_id' => 77,
		'content_blocks'  => array( array( 'client_id' => 'block-heading', 'block_name' => 'core/heading', 'text' => '功能丰富的主题机制' ) ),
		'related_content_evidence' => array( array( 'post_id' => 280979, 'title' => '主题机制详解', 'url' => 'https://example.test/heading-match' ) ),
	)
);
npcink_abilities_toolkit_assert_true( empty( $heading_match_result['data']['internal_link_candidates']['items'][0]['source_match'] ?? array() ), 'resolve-internal-link-targets never proposes an automatic match inside a heading block' );
$generic_phrase_result = $core_read_package->resolve_internal_link_targets(
	array(
		'current_post_id' => 77,
		'content_blocks'  => array( array( 'client_id' => 'block-generic', 'block_name' => 'core/paragraph', 'text' => '本文介绍主题相关配置。' ) ),
		'related_content_evidence' => array( array( 'post_id' => 280980, 'title' => '主题', 'url' => 'https://example.test/generic-anchor' ) ),
	)
);
npcink_abilities_toolkit_assert_true( empty( $generic_phrase_result['data']['internal_link_candidates']['items'][0]['source_match'] ?? array() ), 'resolve-internal-link-targets rejects an unselected generic two-character anchor' );
$GLOBALS['npcink_abilities_toolkit_unit_comments'][21] = (object) array(
	'comment_ID'       => 21,
	'comment_post_ID'  => 77,
	'comment_author'   => 'Ops Reader',
	'comment_approved' => 'hold',
	'comment_content'  => 'Please review this operations comment.',
);
$GLOBALS['npcink_abilities_toolkit_unit_terms'] = array(
	'category' => array(
		(object) array(
			'term_id'     => 301,
			'name'        => 'Workflow',
			'slug'        => 'workflow',
			'description' => '',
			'count'       => 0,
			'parent'      => 0,
		),
	),
);
$site_operations = $core_read_package->get_site_operations_dashboard(
	array(
		'post_type' => 'post',
		'per_page'  => 5,
	)
);
npcink_abilities_toolkit_assert_same( true, $site_operations['success'] ?? null, 'get-site-operations-dashboard returns a success envelope' );
npcink_abilities_toolkit_assert_true( isset( $site_operations['data']['status_counts']['draft'] ), 'get-site-operations-dashboard returns status counts' );
npcink_abilities_toolkit_assert_true( (int) ( $site_operations['data']['comments']['pending_count'] ?? 0 ) >= 1, 'get-site-operations-dashboard counts pending comments' );
$publish_risk = $core_read_package->get_post_publish_risk_report(
	array(
		'post_id'       => 77,
		'focus_keyword' => 'workflow',
	)
);
npcink_abilities_toolkit_assert_same( true, $publish_risk['success'] ?? null, 'get-post-publish-risk-report returns a success envelope' );
npcink_abilities_toolkit_assert_same( 77, $publish_risk['data']['post']['post_id'] ?? null, 'get-post-publish-risk-report keeps post id' );
npcink_abilities_toolkit_assert_true( (int) ( $publish_risk['data']['risk_score'] ?? 0 ) > 0, 'get-post-publish-risk-report returns a positive risk score for incomplete drafts' );
$GLOBALS['npcink_abilities_toolkit_unit_current_user_caps'] = array( 'edit_post' => false );
$denied_risk_report = $core_read_package->get_post_publish_risk_report(
	array(
		'post_id' => 77,
	)
);
npcink_abilities_toolkit_assert_true( is_wp_error( $denied_risk_report ), 'get-post-publish-risk-report denies posts the caller cannot edit' );
npcink_abilities_toolkit_assert_same( 'npcink_abilities_toolkit_permission_denied', is_wp_error( $denied_risk_report ) ? $denied_risk_report->get_error_code() : '', 'get-post-publish-risk-report uses the stable permission-denied error code' );
$calendar_filtered = $core_read_package->get_publishing_calendar_context(
	array(
		'post_type' => 'post',
	)
);
npcink_abilities_toolkit_assert_same( true, $calendar_filtered['success'] ?? null, 'get-publishing-calendar-context still succeeds without per-post edit caps' );
npcink_abilities_toolkit_assert_same( array(), $calendar_filtered['data']['draft_backlog'] ?? null, 'get-publishing-calendar-context filters backlog rows for posts the caller cannot edit' );
npcink_abilities_toolkit_assert_same( array(), $calendar_filtered['data']['scheduled'] ?? null, 'get-publishing-calendar-context filters scheduled rows for posts the caller cannot edit' );
unset( $GLOBALS['npcink_abilities_toolkit_unit_current_user_caps'] );
$calendar_full = $core_read_package->get_publishing_calendar_context(
	array(
		'post_type' => 'post',
	)
);
npcink_abilities_toolkit_assert_true( count( $calendar_full['data']['draft_backlog'] ?? array() ) >= 1, 'get-publishing-calendar-context includes rows for posts the caller can edit' );
npcink_abilities_toolkit_assert_true(
	in_array( 77, array_map( static fn( $row ) => (int) ( $row['post_id'] ?? 0 ), (array) ( $calendar_full['data']['draft_backlog'] ?? array() ) ), true ),
	'get-publishing-calendar-context restores the editable post row after the capability denial block'
);
$article_publish_preflight = $core_read_package->get_article_publish_preflight_context(
	array(
		'post_id'       => 77,
		'focus_keyword' => 'workflow',
		'window_days'   => 30,
	)
);
npcink_abilities_toolkit_assert_same( true, $article_publish_preflight['success'] ?? null, 'get-article-publish-preflight-context returns a success envelope' );
npcink_abilities_toolkit_assert_same( 'npcink-abilities-toolkit/recipes/article-publish-preflight', $article_publish_preflight['data']['recipe'] ?? '', 'get-article-publish-preflight-context declares its recipe id' );
npcink_abilities_toolkit_assert_true( in_array( 'publish_risk', $article_publish_preflight['data']['sections'] ?? array(), true ), 'get-article-publish-preflight-context includes publish risk' );
$refresh_opportunities = $core_read_package->get_content_refresh_opportunities(
	array(
		'post_type'      => 'post',
		'status'         => 'any',
		'per_page'       => 5,
		'stale_days'     => 30,
		'min_word_count' => 200,
	)
);
npcink_abilities_toolkit_assert_same( true, $refresh_opportunities['success'] ?? null, 'get-content-refresh-opportunities returns a success envelope' );
npcink_abilities_toolkit_assert_true( (int) ( $refresh_opportunities['data']['summary']['opportunity_count'] ?? 0 ) >= 1, 'get-content-refresh-opportunities finds refresh candidates' );
npcink_abilities_toolkit_assert_true( isset( $refresh_opportunities['data']['issue_counts']['thin_content'] ), 'get-content-refresh-opportunities counts thin content' );
$GLOBALS['npcink_abilities_toolkit_unit_style_posts'][77]->post_content = 'Optimization context content with <a href="https://example.test/?p=78">workflow candidate</a>.';
$internal_link_graph = $core_read_package->get_internal_link_graph_health(
	array(
		'post_type' => 'post',
		'status'    => 'any',
		'per_page'  => 5,
	)
);
npcink_abilities_toolkit_assert_same( true, $internal_link_graph['success'] ?? null, 'get-internal-link-graph-health returns a success envelope' );
npcink_abilities_toolkit_assert_true( (int) ( $internal_link_graph['data']['summary']['scanned_count'] ?? 0 ) >= 1, 'get-internal-link-graph-health scans local posts' );
npcink_abilities_toolkit_assert_true( isset( $internal_link_graph['data']['issue_counts']['orphan_post'] ), 'get-internal-link-graph-health counts orphan posts' );
$old_article_refresh = $core_read_package->get_old_article_refresh_context(
	array(
		'post_type'     => 'post',
		'status'        => 'any',
		'per_page'      => 5,
		'topic_seed'    => 'workflow',
		'post_id'       => 77,
		'focus_keyword' => 'workflow',
	)
);
npcink_abilities_toolkit_assert_same( true, $old_article_refresh['success'] ?? null, 'get-old-article-refresh-context returns a success envelope' );
npcink_abilities_toolkit_assert_same( 'npcink-abilities-toolkit/recipes/old-article-refresh-discovery', $old_article_refresh['data']['recipe'] ?? '', 'get-old-article-refresh-context declares its recipe id' );
npcink_abilities_toolkit_assert_true( in_array( 'seo_geo_gap_report', $old_article_refresh['data']['sections'] ?? array(), true ), 'get-old-article-refresh-context includes SEO/GEO gaps' );
$GLOBALS['npcink_abilities_toolkit_unit_style_posts'][79] = (object) array(
	'ID'             => 79,
	'post_title'     => 'Workflow diagram image',
	'post_status'    => 'inherit',
	'post_type'      => 'attachment',
	'post_excerpt'   => '',
	'post_content'   => '',
	'post_name'      => 'workflow-diagram-image',
	'post_author'    => 7,
	'post_parent'    => 0,
	'post_mime_type' => 'image/jpeg',
);
update_post_meta(
	79,
	'_wp_attachment_metadata',
	array(
		'width'          => 2600,
		'height'         => 1400,
		'file'           => '2026/06/workflow-diagram-image.jpg',
		'filesize'       => 900000,
		'original_image' => 'workflow-diagram-image-original.jpg',
		'sizes'          => array(
			'medium' => array(
				'file'   => 'workflow-diagram-image-300x162.jpg',
				'width'  => 300,
				'height' => 162,
			),
		),
	)
);
update_post_meta( 79, '_wp_attached_file', '2026/06/workflow-diagram-image.jpg' );
$cloud_meta_cas_method = new ReflectionMethod( Core_Write_Package::class, 'cloud_media_atomic_compare_and_swap_post_meta' );
$cloud_meta_cas_method->setAccessible( true );

